### ISSUE TITLE
Beta versioning of libSwiften

### ISSUE THREAD

**Issue by jubalh** [swift/swift#31]
When compiling Swift 4 Beta2 the libSwiften is generated as `libSwiften.so.0` instead of `4`.

[Scons](https://github.com/swift/swift/blob/master/Swiften/SConscript#L15) shows that `SWIFTEN_VERSION` is used to set this. It seems in case of Betas it's not handled correctly. I assumed `SWIFTEN_VERSION` to be: 4.0-beta2 but when I added a print statement I got `20160726`.

**Comment by Kev** [comment]
Date versions instead of the proper ones happen if you use a tarball provided by Github. Swift(en) needs to be built either from one of our versioned tarballs from swift.im, or using a Git checkout. Unfortunately, there doesn't seem to be (that I can see) any way of stopping Github from providing these unhelpful tarballs.

**Comment by jubalh** [comment]
@Kev Thanks! Maybe a hint to not use GitHub releases can be helpful in the Readme.

For others who experience this issue: Upstream tarballs are available at: http://swift.im/downloads/releases/

**Comment by Kev** [comment]
Indeed, we'll add such a note, ta (I was hoping before to work out how to stop Github presenting 'broken' tarballs, but there doesn't seem a way to do such a thing).
