### ISSUE TITLE
Request: Entering ports by service name should work

### ISSUE THREAD

**Issue by SamWhited** [swift/swift#36]
Currently if I enter a port by its IANA registered service name, it fails. Eg. if I enter the BOSH URI `http://localhost:xmpp-bosh/http-bind` I get an error "The provided BOSH URL is not valid", but `xmpp-bosh` is a valid mapping according to my system (`/etc/services` on Linux and Darwin, no idea about other systems).

It would be somewhat nice if this was a bit less strict about validation and let the OS decide if the port was valid or not.

**Comment by Kev** [comment]
Use of service names for the port part of the authority in a URI seems to be illegal to me, they're always numeric - https://tools.ietf.org/html/rfc3986#section-3.2.3

**Comment by SamWhited** [comment]
On Linux at least a lot of things [citation needed] will map the port for you; I thought this was something in libc land somewhere, so I'm not sure Swift would have to do anything itself, just stop doing its own validation and let the OS return an error if the port doesn't exist (or if it can't find a mapping for it). This is totally unresearched from my side though; it could just be that a lot of tools I use do /etc/service lookups and implement this themselves.

**Comment by Kev** [comment]
But inside a URI itself? It seems odd that 'a lot of things' would allow illegal URI entry just for this use case (which seems of relatively limited application, if I'm honest).

I don't think this is something we want to special-case in the URI validation, so I'm closing the issue until someone can persuade me otherwise, sorry Sam.
